---
# tasks file for ansible-role-node-exporter

- name: Validate role inputs
  ansible.builtin.import_tasks: preflight.yml

- name: Create service account
  ansible.builtin.import_tasks: user.yml

- name: Install node_exporter binary
  ansible.builtin.import_tasks: install.yml

- name: Configure node_exporter service
  ansible.builtin.import_tasks: service.yml
